name: Test and Deploy
on: push
jobs:
  lint:
    steps:
      - name: Get Code
        uses: github/checkout@v3
      - name: Install Node
        uses: github/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Lint Code
        run: npm lint
  test:
    needs: lint
    steps:
      - name: Get Code
        uses: github/checkout@v3
      - name: Install Node
        uses: github/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Test Code
        run: npm test
  build:
    needs: test
    steps:
      - name: Get Code
        uses: github/checkout@v3
      - name: Install Node
        uses: github/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm ci
      - name: Test Code
        run: npm build